# Generated by Django 4.2.11 on 2025-05-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_rename_serviceorder_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.PositiveIntegerField(default=250),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_name',
            field=models.CharField(max_length=200),
        ),
    ]
