# Generated by Django 4.2.11 on 2025-05-26 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_order_amount_order_payment_id_order_payment_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
