# Generated by Django 4.2.11 on 2025-05-26 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0006_order_service_provider_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
