# Generated by Django 4.2.11 on 2025-05-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0008_order_status_serviceprovider_order_service_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='user',
        ),
    ]
