# Generated by Django 4.2.11 on 2025-05-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0009_remove_serviceprovider_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='address',
            new_name='callable_of',
        ),
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='service_name',
            new_name='servicer_name',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='employee',
        ),
    ]
