# Generated by Django 4.2.11 on 2025-05-26 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0010_rename_address_serviceprovider_callable_of_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='message',
        ),
    ]
