# Generated by Django 4.2.11 on 2025-05-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0012_serviceprovider_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='password',
            field=models.CharField(default='thisisapassword', max_length=100),
        ),
    ]
