# Generated by Django 4.2.11 on 2025-05-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0013_serviceprovider_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('RejectedByProvider', 'Rejected by Provider')], default='Pending', max_length=20),
        ),
    ]
