# Generated by Django 4.2.11 on 2025-05-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0014_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
