# Generated by Django 4.2.11 on 2025-05-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0015_order_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='mobile_number',
            field=models.CharField(default=9999999999, max_length=10),
            preserve_default=False,
        ),
    ]
